/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inerfaces;

/**
 *
 * @author Abdessamed
 */
public class UserDashboard extends javax.swing.JFrame {

    /**
     * Creates new form UserDashboard
     */
    public UserDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        UserProfil = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        testhome = new javax.swing.JPanel();
        navbar4 = new javax.swing.JPanel();
        SearchNavBar6 = new javax.swing.JPanel();
        IconSearch6 = new javax.swing.JLabel();
        RectangleSearch6 = new javax.swing.JLabel();
        InputSearch6 = new javax.swing.JTextField();
        StudentRegistration = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        SearchNavBar = new javax.swing.JPanel();
        IconSearch = new javax.swing.JLabel();
        RectangleSearch = new javax.swing.JLabel();
        InputSearch = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        StudentReRegistration = new javax.swing.JPanel();
        navbar1 = new javax.swing.JPanel();
        SearchNavBar3 = new javax.swing.JPanel();
        IconSearch3 = new javax.swing.JLabel();
        RectangleSearch3 = new javax.swing.JLabel();
        InputSearch3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TransferStudent = new javax.swing.JPanel();
        navbar2 = new javax.swing.JPanel();
        SearchNavBar4 = new javax.swing.JPanel();
        IconSearch4 = new javax.swing.JLabel();
        RectangleSearch4 = new javax.swing.JLabel();
        InputSearch4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        StudentManagement = new javax.swing.JPanel();
        navbar3 = new javax.swing.JPanel();
        SearchNavBar5 = new javax.swing.JPanel();
        IconSearch5 = new javax.swing.JLabel();
        RectangleSearch5 = new javax.swing.JLabel();
        InputSearch5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(0, 102, 102));

        jButton1.setBackground(new java.awt.Color(23, 82, 82));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inerfaces/enter.png"))); // NOI18N
        jButton1.setText("تسجيل الخروج");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inerfaces/Group 26.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 40, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inerfaces/Vector 2.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 40, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inerfaces/Group 24.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 40, 40));

        jButton6.setBackground(new java.awt.Color(0, 153, 153));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 51, 51));
        jButton6.setText("تسجيل طالب");
        jButton6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 70));

        jButton7.setBackground(new java.awt.Color(0, 153, 153));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 51, 51));
        jButton7.setText("إعادة تسجيل طالب");
        jButton7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 140, 70));

        jButton8.setBackground(new java.awt.Color(0, 153, 153));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 51, 51));
        jButton8.setText("تحويل طالب");
        jButton8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 140, 70));

        UserProfil.setBackground(new java.awt.Color(23, 82, 82));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inerfaces/user.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("عون الحجز");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout UserProfilLayout = new javax.swing.GroupLayout(UserProfil);
        UserProfil.setLayout(UserProfilLayout);
        UserProfilLayout.setHorizontalGroup(
            UserProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserProfilLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(UserProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UserProfilLayout.setVerticalGroup(
            UserProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserProfilLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inerfaces/Group 27.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 153, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 51));
        jButton4.setText("إدارة الطلبة");
        jButton4.setPreferredSize(new java.awt.Dimension(90, 40));
        jButton4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 105, 70));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inerfaces/medical-record (3).png"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 51));
        jButton2.setText("التسجيلات");
        jButton2.setPreferredSize(new java.awt.Dimension(90, 40));
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 105, 70));

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserProfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addGroup(menuLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addComponent(UserProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanel1.setVisible(false);

        home.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 210, 740));

        testhome.setBackground(new java.awt.Color(255, 255, 255));

        navbar4.setBackground(new java.awt.Color(0, 102, 102));
        navbar4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchNavBar6.setBackground(new java.awt.Color(0, 102, 102));

        IconSearch6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inerfaces/loupe (1).png"))); // NOI18N

        RectangleSearch6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inerfaces/Rectangle 4.png"))); // NOI18N

        InputSearch6.setBackground(new java.awt.Color(0, 102, 102));
        InputSearch6.setBorder(null);

        javax.swing.GroupLayout SearchNavBar6Layout = new javax.swing.GroupLayout(SearchNavBar6);
        SearchNavBar6.setLayout(SearchNavBar6Layout);
        SearchNavBar6Layout.setHorizontalGroup(
            SearchNavBar6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchNavBar6Layout.createSequentialGroup()
                .addContainerGap(327, Short.MAX_VALUE)
                .addComponent(IconSearch6)
                .addGap(19, 19, 19))
            .addGroup(SearchNavBar6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchNavBar6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RectangleSearch6)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(SearchNavBar6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchNavBar6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InputSearch6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        SearchNavBar6Layout.setVerticalGroup(
            SearchNavBar6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchNavBar6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(IconSearch6)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(SearchNavBar6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchNavBar6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RectangleSearch6)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(SearchNavBar6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchNavBar6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InputSearch6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        navbar4.add(SearchNavBar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        javax.swing.GroupLayout testhomeLayout = new javax.swing.GroupLayout(testhome);
        testhome.setLayout(testhomeLayout);
        testhomeLayout.setHorizontalGroup(
            testhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navbar4, javax.swing.GroupLayout.DEFAULT_SIZE, 1090, Short.MAX_VALUE)
        );
        testhomeLayout.setVerticalGroup(
            testhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testhomeLayout.createSequentialGroup()
                .addComponent(navbar4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(680, Short.MAX_VALUE))
        );

        home.add(testhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 740));

        StudentRegistration.setBackground(new java.awt.Color(0, 153, 153));

        navbar.setBackground(new java.awt.Color(0, 102, 102));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchNavBar.setBackground(new java.awt.Color(0, 102, 102));

        IconSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inerfaces/loupe (1).png"))); // NOI18N

        RectangleSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inerfaces/Rectangle 4.png"))); // NOI18N

        InputSearch.setBackground(new java.awt.Color(0, 102, 102));
        InputSearch.setBorder(null);

        javax.swing.GroupLayout SearchNavBarLayout = new javax.swing.GroupLayout(SearchNavBar);
        SearchNavBar.setLayout(SearchNavBarLayout);
        SearchNavBarLayout.setHorizontalGroup(
            SearchNavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchNavBarLayout.createSequentialGroup()
                .addContainerGap(327, Short.MAX_VALUE)
                .addComponent(IconSearch)
                .addGap(19, 19, 19))
            .addGroup(SearchNavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchNavBarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RectangleSearch)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(SearchNavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchNavBarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        SearchNavBarLayout.setVerticalGroup(
            SearchNavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchNavBarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(IconSearch)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(SearchNavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchNavBarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RectangleSearch)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(SearchNavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchNavBarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        navbar.add(SearchNavBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel4.setText("stdreg");

        javax.swing.GroupLayout StudentRegistrationLayout = new javax.swing.GroupLayout(StudentRegistration);
        StudentRegistration.setLayout(StudentRegistrationLayout);
        StudentRegistrationLayout.setHorizontalGroup(
            StudentRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(StudentRegistrationLayout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(jLabel4)
                .addContainerGap(660, Short.MAX_VALUE))
        );
        StudentRegistrationLayout.setVerticalGroup(
            StudentRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentRegistrationLayout.createSequentialGroup()
                .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252)
                .addComponent(jLabel4)
                .addGap(0, 412, Short.MAX_VALUE))
        );

        home.add(StudentRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 740));
        StudentRegistration.setVisible(false);

        StudentReRegistration.setBackground(new java.awt.Color(0, 153, 153));

        navbar1.setBackground(new java.awt.Color(0, 102, 102));
        navbar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchNavBar3.setBackground(new java.awt.Color(0, 102, 102));

        IconSearch3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inerfaces/loupe (1).png"))); // NOI18N

        RectangleSearch3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inerfaces/Rectangle 4.png"))); // NOI18N

        InputSearch3.setBackground(new java.awt.Color(0, 102, 102));
        InputSearch3.setBorder(null);

        javax.swing.GroupLayout SearchNavBar3Layout = new javax.swing.GroupLayout(SearchNavBar3);
        SearchNavBar3.setLayout(SearchNavBar3Layout);
        SearchNavBar3Layout.setHorizontalGroup(
            SearchNavBar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchNavBar3Layout.createSequentialGroup()
                .addContainerGap(327, Short.MAX_VALUE)
                .addComponent(IconSearch3)
                .addGap(19, 19, 19))
            .addGroup(SearchNavBar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchNavBar3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RectangleSearch3)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(SearchNavBar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchNavBar3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InputSearch3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        SearchNavBar3Layout.setVerticalGroup(
            SearchNavBar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchNavBar3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(IconSearch3)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(SearchNavBar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchNavBar3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RectangleSearch3)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(SearchNavBar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchNavBar3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InputSearch3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        navbar1.add(SearchNavBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel5.setText("stdrereg");

        javax.swing.GroupLayout StudentReRegistrationLayout = new javax.swing.GroupLayout(StudentReRegistration);
        StudentReRegistration.setLayout(StudentReRegistrationLayout);
        StudentReRegistrationLayout.setHorizontalGroup(
            StudentReRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navbar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1090, Short.MAX_VALUE)
            .addGroup(StudentReRegistrationLayout.createSequentialGroup()
                .addGap(438, 438, 438)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StudentReRegistrationLayout.setVerticalGroup(
            StudentReRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentReRegistrationLayout.createSequentialGroup()
                .addComponent(navbar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 350, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(314, 314, 314))
        );

        home.add(StudentReRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 740));
        StudentReRegistration.setVisible(false);

        TransferStudent.setBackground(new java.awt.Color(0, 153, 153));

        navbar2.setBackground(new java.awt.Color(0, 102, 102));
        navbar2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchNavBar4.setBackground(new java.awt.Color(0, 102, 102));

        IconSearch4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inerfaces/loupe (1).png"))); // NOI18N

        RectangleSearch4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inerfaces/Rectangle 4.png"))); // NOI18N

        InputSearch4.setBackground(new java.awt.Color(0, 102, 102));
        InputSearch4.setBorder(null);

        javax.swing.GroupLayout SearchNavBar4Layout = new javax.swing.GroupLayout(SearchNavBar4);
        SearchNavBar4.setLayout(SearchNavBar4Layout);
        SearchNavBar4Layout.setHorizontalGroup(
            SearchNavBar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchNavBar4Layout.createSequentialGroup()
                .addContainerGap(327, Short.MAX_VALUE)
                .addComponent(IconSearch4)
                .addGap(19, 19, 19))
            .addGroup(SearchNavBar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchNavBar4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RectangleSearch4)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(SearchNavBar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchNavBar4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InputSearch4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        SearchNavBar4Layout.setVerticalGroup(
            SearchNavBar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchNavBar4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(IconSearch4)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(SearchNavBar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchNavBar4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RectangleSearch4)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(SearchNavBar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchNavBar4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InputSearch4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        navbar2.add(SearchNavBar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel6.setText("trsf");

        javax.swing.GroupLayout TransferStudentLayout = new javax.swing.GroupLayout(TransferStudent);
        TransferStudent.setLayout(TransferStudentLayout);
        TransferStudentLayout.setHorizontalGroup(
            TransferStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navbar2, javax.swing.GroupLayout.DEFAULT_SIZE, 1090, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TransferStudentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(519, 519, 519))
        );
        TransferStudentLayout.setVerticalGroup(
            TransferStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransferStudentLayout.createSequentialGroup()
                .addComponent(navbar2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(263, 263, 263)
                .addComponent(jLabel6)
                .addGap(0, 401, Short.MAX_VALUE))
        );

        home.add(TransferStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 740));
        TransferStudent.setVisible(false);

        StudentManagement.setBackground(new java.awt.Color(0, 153, 153));

        navbar3.setBackground(new java.awt.Color(0, 102, 102));
        navbar3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchNavBar5.setBackground(new java.awt.Color(0, 102, 102));

        IconSearch5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inerfaces/loupe (1).png"))); // NOI18N

        RectangleSearch5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inerfaces/Rectangle 4.png"))); // NOI18N

        InputSearch5.setBackground(new java.awt.Color(0, 102, 102));
        InputSearch5.setBorder(null);

        javax.swing.GroupLayout SearchNavBar5Layout = new javax.swing.GroupLayout(SearchNavBar5);
        SearchNavBar5.setLayout(SearchNavBar5Layout);
        SearchNavBar5Layout.setHorizontalGroup(
            SearchNavBar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchNavBar5Layout.createSequentialGroup()
                .addContainerGap(327, Short.MAX_VALUE)
                .addComponent(IconSearch5)
                .addGap(19, 19, 19))
            .addGroup(SearchNavBar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchNavBar5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RectangleSearch5)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(SearchNavBar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchNavBar5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InputSearch5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        SearchNavBar5Layout.setVerticalGroup(
            SearchNavBar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchNavBar5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(IconSearch5)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(SearchNavBar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchNavBar5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RectangleSearch5)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(SearchNavBar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchNavBar5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InputSearch5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        navbar3.add(SearchNavBar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel7.setText("stdm");

        javax.swing.GroupLayout StudentManagementLayout = new javax.swing.GroupLayout(StudentManagement);
        StudentManagement.setLayout(StudentManagementLayout);
        StudentManagementLayout.setHorizontalGroup(
            StudentManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navbar3, javax.swing.GroupLayout.DEFAULT_SIZE, 1090, Short.MAX_VALUE)
            .addGroup(StudentManagementLayout.createSequentialGroup()
                .addGap(517, 517, 517)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StudentManagementLayout.setVerticalGroup(
            StudentManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentManagementLayout.createSequentialGroup()
                .addComponent(navbar3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204)
                .addComponent(jLabel7)
                .addGap(0, 460, Short.MAX_VALUE))
        );

        home.add(StudentManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 740));
        StudentManagement.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1300, 746));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       // System.exit(0);
       Login back =new Login();
       back.show();
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(jPanel1.isVisible()){
            jPanel1.setVisible(false);
        }else{
            jPanel1.setVisible(true); 
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       StudentRegistration.setVisible(false);
        StudentManagement.setVisible(true);
        TransferStudent.setVisible(false);
        StudentReRegistration.setVisible(false);
        testhome.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        StudentRegistration.setVisible(true);
        StudentManagement.setVisible(false);
        TransferStudent.setVisible(false);
        StudentReRegistration.setVisible(false);
        testhome.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        StudentRegistration.setVisible(false);
        StudentManagement.setVisible(false);
        TransferStudent.setVisible(false);
        StudentReRegistration.setVisible(true);
        testhome.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        StudentRegistration.setVisible(false);
        StudentManagement.setVisible(false);
        TransferStudent.setVisible(true);
        StudentReRegistration.setVisible(false);
        testhome.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconSearch;
    private javax.swing.JLabel IconSearch3;
    private javax.swing.JLabel IconSearch4;
    private javax.swing.JLabel IconSearch5;
    private javax.swing.JLabel IconSearch6;
    private javax.swing.JTextField InputSearch;
    private javax.swing.JTextField InputSearch3;
    private javax.swing.JTextField InputSearch4;
    private javax.swing.JTextField InputSearch5;
    private javax.swing.JTextField InputSearch6;
    private javax.swing.JLabel RectangleSearch;
    private javax.swing.JLabel RectangleSearch3;
    private javax.swing.JLabel RectangleSearch4;
    private javax.swing.JLabel RectangleSearch5;
    private javax.swing.JLabel RectangleSearch6;
    private javax.swing.JPanel SearchNavBar;
    private javax.swing.JPanel SearchNavBar3;
    private javax.swing.JPanel SearchNavBar4;
    private javax.swing.JPanel SearchNavBar5;
    private javax.swing.JPanel SearchNavBar6;
    private javax.swing.JPanel StudentManagement;
    private javax.swing.JPanel StudentReRegistration;
    private javax.swing.JPanel StudentRegistration;
    private javax.swing.JPanel TransferStudent;
    private javax.swing.JPanel UserProfil;
    private javax.swing.JPanel home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel navbar;
    private javax.swing.JPanel navbar1;
    private javax.swing.JPanel navbar2;
    private javax.swing.JPanel navbar3;
    private javax.swing.JPanel navbar4;
    private javax.swing.JPanel testhome;
    // End of variables declaration//GEN-END:variables
}
